### ISSUE TITLE
Hardware Specifications

### ISSUE THREAD

**Issue by ryanvade** [kipr/wallaby#19] opened 2016-08-31 16:26 UTC
I'm going to start working on a GPU acceleration library for the Wallaby.   I have access to a wallaby but some hardware specifications would be nice.  And information on the Yocto install would be helpful as well.  From what I understand the system is running on an gumstixx overo? Or is it a duvero?

**Comment by jsoutherland** [comment] 2016-08-31 16:58
@ryanvade  Thanks for your interest. 


This repo is for the co-processor (STM32F4) firmware.  You will likely be modifying only main processor (AM3354).  You will probably mostly be working off our yocto bitbake setup at: https://github.com/kipr/meta-kipr


We are running a custom board, based on Gumstix's Geppeto offerings.  I'm unsure how similar it is to overo/duovero.


We have a schematic at https://github.com/kipr/wallaby/blob/master/docs/schematic_v7.pdf that you can pull part numbers off of.

I have old install notes for  an Ubuntu 14.04 VM. I will provide those notes here and will try to confirm those steps and add them as a meta-kipr readme soon.


***Build server setup***
Based on https://github.com/gumstix/yocto-manifest
````
$ sudo apt-get install git g++ binutils diffstat chrpath make texinfo configure gitconfig npm libboost-dev

$ sudo mkdir /usr/local/lib/node_modules
$ sudo chown <user> /usr/local/lib/node_mdules

$ curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > repo
$ chmod a+x repo
$ sudo mv repo /usr/local/bin/

$ mkdir yocto
$ cd yocto

$ repo init -u git://github.com/gumstix/yocto-manifest.git
$ repo sync

$ cd poky
$ git clone https://github.com/kipr/meta-kipr.git
$ git clone https://github.com/meta-qt5/meta-qt5.git
$ git clone https://github.com/OSSystems/meta-browser.git
(in meta-browser, checkout e114d62)
$ git clone https://github.com/imyller/meta-nodejs.git
$ cd ..   (to yocto)

$ export TEMPLATECONF=meta-kipr/conf
$ . poky/oe-init-build-env   (moves you to yocto/build)
$ vim conf/bblayers.conf (add line to BBLAYERS for meta-nodejs, probably not needed now TODO: check)
$ cd ..    (to yocto)
````

Now to build you should just have to run these in ``yocto/``
````bash
$ . poky/oe-init-build-env    
$ bitbake kipr-console-image
````

...but harrogate has been breaking lately, I have to run these commands before ``bitbake kipr-console-image`` :
````bash
. poky/oe-init-build-env
npm config set prefix '~/.npm-global'
export PATH=~/.npm-global/bin:$PATH
source ~/.profile
````

Where the .profile file contains:
````
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
````

Hope this helps,

Josh

**Comment by ryanvade** [comment] 2016-09-06 18:36
So far I have been unable to build harrogate. 
```
ERROR: ParseError at /home/ryan/yocto/poky/meta-kipr/recipes-apps/harrogate/harrogate_git.bb:1: Could not inherit file classes/npm-install.bbclass
```

**Comment by jsoutherland** [comment] 2016-09-07 14:06
@ryanvade sorry about that, I will work through a new build server setup today and see if I can replicate it.

Can you post the contents of  ``yocto/build/conf/bblayers.conf`` ?

**Comment by jsoutherland** [comment] 2016-09-07 14:09
If npm-install is missing, it is probably that   ``yocto/poky/meta-nodejs`` is missing.

Did you clone meta-nodejs above into ``yocto/poky``?:
``git clone https://github.com/imyller/meta-nodejs.git``

**Comment by ryanvade** [comment] 2016-09-12 17:29
bblayers.conf
```
# LAYER_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
LCONF_VERSION = "6"

BBPATH = "${TOPDIR}"
BBFILES ?= ""
BBLAYERS ?= " \
  /home/ryan/geppeto/poky/meta \
  /home/ryan/geppeto/poky/meta-yocto \
  /home/ryan/geppeto/poky/meta-openembedded/meta-gnome \
  /home/ryan/geppeto/poky/meta-openembedded/meta-oe \
  /home/ryan/geppeto/poky/meta-openembedded/meta-xfce \
  /home/ryan/geppeto/poky/meta-openembedded/meta-systemd \
  /home/ryan/geppeto/poky/meta-openembedded/meta-networking \
  /home/ryan/geppeto/poky/meta-openembedded/meta-multimedia \
  /home/ryan/geppeto/poky/meta-openembedded/meta-python \
  /home/ryan/geppeto/poky/meta-gumstix \
  /home/ryan/geppeto/poky/meta-gumstix-extras \
  /home/ryan/geppeto/poky/meta-kipr \
  /home/ryan/geppeto/poky/meta-qt5 \
  /home/ryan/geppeto/poky/meta-ros \
  /home/ryan/geppeto/poky/meta-ti \
  /home/ryan/geppeto/poky/meta-browser \
  /home/ryan/geppeto/poky/meta-nodejs \
  "

BBMASK = "meta-ti/recipes-kernel"
```

**Comment by ryanvade** [comment] 2016-09-12 17:51
Does not work on Ubuntu 14.04 either. 
```
bitbake kipr-console-image
NOTE: Started PRServer with DBfile: /home/ryan/gepetto/build/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 46570, PID: 4604
ERROR: ParseError at /home/ryan/gepetto/poky/meta-qt5/classes/qmake5_base.bbclass:50: Could not inherit file classes/remove-libtool.bbclass                                                                                                                               | ETA:  00:00:41

Summary: There was 1 ERROR message shown, returning a non-zero exit code.

```

**Comment by jsoutherland** [comment] 2016-09-12 20:18
I haven't tried on 16.04 yet.

I have worked through 14.04 on Friday again and found several errors like the meta-qt5 one you ran into.  I got things working finally but it took a lot of manual intervention along the way so I am trying to make it go more smoothly.   

One way I am improving things is by creating https://github.com/kipr/yocto-manifest/pull/1
That will get us around many errors caused by using the latest master. It will also remove all manual git clone steps and editing bblayers.

As far as meta-qt5 goes... you can see I fixed it by checking out commit (51b4620392aa9041d8512549bfa554bea368c5ea) at https://github.com/kipr/yocto-manifest/pull/1/files#diff-93c1b4ece00d8947182838b3a5d8ce21R26

I am still working through that and hope to have it soon.... I'm sorry this has been a slow down.

**Comment by ryanvade** [comment] 2016-09-14 14:38
I ran into this error using  kipr/yocto-manifest#1 :
```
| npm ERR!
| npm ERR! Additional logging details can be found in:
| npm ERR!     /home/ryan/gepetto/build/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/harrogate/git-74/git/npm-debug.log
| npm ERR! not ok code 0
| ERROR: oe_runnpm failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/ryan/gepetto/build/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/harrogate/git-74/temp/log.do_compile.12605)
ERROR: Task 1126 (/home/ryan/gepetto/poky/meta-kipr/recipes-apps/harrogate/harrogate_git.bb, do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4104 tasks of which 0 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
  /home/ryan/gepetto/poky/meta-kipr/recipes-apps/harrogate/harrogate_git.bb, do_compile
Summary: There were 27 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code
```
I used these commands to try and fix:
```
. poky/oe-init-build-env
npm config set prefix '~/.npm-global'
export PATH=~/.npm-global/bin:$PATH
source ~/.profile
```
with the same result. 

[npm-debug-log.txt](https://github.com/kipr/wallaby/files/472295/npm-debug-log.txt)
[log-do_compile-12605.txt](https://github.com/kipr/wallaby/files/472299/log-do_compile-12605.txt)

**Comment by jsoutherland** [comment] 2016-09-14 19:36
It is using ``'/home/ryan/tmp/npm-16812-SER5E4Ko/...`` which is something I haven't seen yet.

Try again with
````
. poky/oe-init-build-env
npm config set prefix '~/.npm-global'
export PATH=~/.npm-global/bin:$PATH
source ~/.profile
bitbake -c clean harrogate
bitbake harrogate
````


If it fails try one more 
`` bitbake harrogate`` 
in the same session. For some reason harrogate can fail the very first time... I'm trying to figure that out. It looks like the npm config fix doesn't work until harrogate has failed once.

**Comment by ryanvade** [comment] 2016-09-14 22:44
```
| ERROR: oe_runnpm failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/ryan/gepetto/build/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/harrogate/git-74/temp/log.do_compile.32605)
ERROR: Task 6 (/home/ryan/gepetto/poky/meta-kipr/recipes-apps/harrogate/harrogate_git.bb, do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 690 tasks of which 689 didn't need to be rerun and 1 failed.
No currently running tasks (532 of 700)

Summary: 1 task failed:
  /home/ryan/gepetto/poky/meta-kipr/recipes-apps/harrogate/harrogate_git.bb, do_compile
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
```

**Comment by ryanvade** [comment] 2016-09-14 22:46
Tried and failed. 
[build_error.txt](https://github.com/kipr/wallaby/files/473609/build_error.txt)

**Comment by jsoutherland** [comment] 2016-09-14 22:55
I will get a new vm working with my latest improvements and post the steps. That may be more straightforward.

**Comment by jsoutherland** [comment] 2016-09-15 15:15
I am working through a fresh install today.

I noticed a hard coded path in the Harrogate recipe that may be causing the issue you ran into:
https://github.com/kipr/meta-kipr/blob/master/recipes-apps/harrogate/harrogate_git.bb#L25

**Comment by jsoutherland** [comment] 2016-09-15 19:59
I made it past harrogate building so it will probably succeed:

I started on a clean 14.04 Ubuntu VM
````
$ sudo apt-get install git g++ binutils diffstat chrpath make texinfo npm nodejs-legacy libboost-dev gawk

````

I set up gitconfig
````
$ git config --global user.email "you@example.com"
$ git config --global user.name "Your Name"
````

I then got the repo tool and set up our sources. This is more simple than it would have been before:
````
$ curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > repo
$ chmod a+x repo
$ sudo mv repo /usr/local/bin/

$ mkdir yocto
$ cd yocto
$ repo init -u git://github.com/kipr/yocto-manifest.git -b kipr-wallaby
$ repo sync
````

You will have to fix the SYSROOT path in ``yocto/poky/meta-kipr/recipes-apps/harrogate/harrogate_git.bb``:
https://github.com/kipr/meta-kipr/blob/master/recipes-apps/harrogate/harrogate_git.bb#L25

Configure more path stuff and the build:
````
$ export TEMPLATECONF=meta-kipr/conf
$ npm config set prefix '~/.npm-global'
$ export PATH=~/.npm-global/bin:$PATH
$ source ~/.profile
$ . poky/oe-init-build-env        (moves you to yocto/build)
````

Build harrogate first, since it is the most likely package to cause problems:
````
$ bitbake harrogate
````

I get the error
````
ERROR: QA Issue: harrogate: The compile log indicates that host include and/or library paths were used.
  Please check the log '/home/kipr/yocto/build/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/harrogate/git-74/temp/log.do_compile' for more information. [compile-host-path]
WARNING: QA Issue: harrogate requires /bin/bash, but no providers in its RDEPENDS [file-rdeps]
ERROR: QA run found fatal errors. Please consider fixing them.
ERROR: Function failed: do_package_qa
ERROR: Logfile of failure stored in: /home/kipr/yocto/build/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/harrogate/git-74/temp/log.do_package_qa.7084
ERROR: Task 10 (/home/kipr/yocto/poky/meta-kipr/recipes-apps/harrogate/harrogate_git.bb, do_package_qa) failed with exit code '1'
````

The following resolves it:
````
$ bitbake -c clean harrogate
$ bitbake harrogate
````

Now build the rest of the image:
````
$ bitbake kipr-console-image
````

**Comment by ryanvade** [comment] 2016-09-16 01:27
Any particular reason to use nodejs-legacy instead of nodejs?

**Comment by jsoutherland** [comment] 2016-09-16 12:12
I think it was just because open embedded requires ``node`` instead of ``nodejs``.  If the harrogate.bb recipe or meta-nodejs setup were fixed so that a system version of node wasn't used it would remove that apt-get and maybe fix our other first-time build issue.

**Comment by ryanvade** [comment] 2016-09-19 16:11
I was able to complete the build using your steps.

**Comment by jsoutherland** [comment] 2016-09-20 13:51
@ryanvade I'm going to close this issue for now.  If anything new comes up we can follow-up in https://github.com/kipr/meta-kipr

I think that your work would either end up in meta-kipr, or a new repo included in the build by meta-kipr.

**Closed by jsoutherland** 2016-09-20 13:51 UTC
